import torch

checkpoint = torch.load("BPNN_adam.pt")
# print(checkpoint['hidden11.weight'])
# print(checkpoint['hidden11.bias'])
# print(checkpoint['hidden22.weight'])
# print(checkpoint['hidden22.bias'])
# print(checkpoint['hidden33.weight'])
# print(checkpoint['hidden33.bias'])
# print(checkpoint['hidden44.weight'])
# print(checkpoint['hidden44.bias'])
# print(checkpoint['hidden55.weight'])
# print(checkpoint['hidden55.bias'])
# print(checkpoint['hidden66.weight'])
# print(checkpoint['hidden66.bias'])
# print(checkpoint['hidden77.weight'])
# print(checkpoint['hidden77.bias'])
# print(checkpoint['predict.weight'])
# print(checkpoint['predict.bias'])
print(checkpoint)